name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - run: git --version
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: false
          tags: test:latest
